name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  easy_refresh: ^3.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  loading_animation_widget: ^1.2.1
  random_name_generator: ^1.3.0
  record_iterable_utils: ^0.1.0
  riverpod_annotation: ^2.3.5
  riverpod_paging_utils:
    path: ../

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  grinder: ^0.9.5
  k9i_cli: ^1.1.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  yumemi_lints: ^2.1.0

flutter:
  uses-material-design: true
