name: riverpod_paging_utils
repository: https://github.com/K9i-0/riverpod_paging_utils
packages:
  - .
  - example

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.0.0"
    dependencies:
      flutter_riverpod: ^2.5.1
      freezed_annotation: ^2.4.1
      visibility_detector: ^0.4.0+2
    dev_dependencies:
      build_runner: ^2.4.9
      freezed: ^2.5.2
      yumemi_lints: ^2.1.0
      
scripts:
  build:
    run: dart run build_runner build -d
    packageFilters:
      dependsOn: build_runner

  watch:
    run: dart run build_runner watch -d
    packageFilters:
      dependsOn: build_runner