name: riverpod_paging_utils
sdkPath: .fvm/flutter_sdk
repository: https://github.com/K9i-0/riverpod_paging_utils

packages:
  - .
  - example

command:
  bootstrap:
    environment:
      sdk: ">=3.6.0 <4.0.0"
      flutter: ">=3.27.0"
    dependencies:
      flutter_riverpod: ^2.6.1
      freezed_annotation: ^3.0.0
      visibility_detector: ^0.4.0+2
    dev_dependencies:
      build_runner: ^2.4.15
      freezed: ^3.0.6
      yumemi_lints: ^3.1.0
    hooks:
      post: melos run yumemi_lints_update
      
scripts:
  h:
    description: Show help
    run: dart run scripts/help.dart

  build:
    description: build_runner build
    exec: dart run build_runner build -d
    packageFilters:
      dependsOn: build_runner

  watch:
    description: build_runner watch
    exec: dart run build_runner watch -d
    packageFilters:
      dependsOn: build_runner

  yumemi_lints_update:
    description: Update yumemi_lints configuration
    exec: dart run yumemi_lints update
    packageFilters:
      dependsOn: yumemi_lints