name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        version: latest
        install: true
        cache: true
        experimental: true

    - name: Install Flutter via mise
      run: |
        mise install
        echo "$(mise where flutter)/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Flutter installation
      run: flutter --version
      shell: bash

    - name: Install dependencies
      run: dart pub get
      shell: bash