# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+*' # for tags like: '1.2.3'

jobs:
  increment_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Update pubspec.yaml
        run: |
          yq eval '.version = "${{ steps.vars.outputs.tag }}"' pubspec.yaml -i
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pubspec.yaml
          git commit -m "Update pubspec.yaml version to ${{ steps.vars.outputs.tag }}"
          git push origin main

  publish:
    needs: increment_version
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # Specify the github actions deployment environment
      environment: pub.dev
      # working-directory: path/to/package/within/repository