# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+*' # for tags like: '1.2.3'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # setup OIDC token
      - uses: dart-lang/setup-dart@v1

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Run tests
        run: flutter test
        
      - name: Publish
        run: dart pub publish --force