# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.APP_ID_OF_K9I_TAG_PUSHER }}
        private-key: ${{ secrets.APP_PRIVATE_KEY_OF_K9I_TAG_PUSHER }}

    - uses: actions/checkout@v4
      with:
        token: ${{ steps.generate_token.outputs.token }}

    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

    - name: Get current version from pubspec.yaml
      id: get_current_version
      run: |
        current_version=$(yq eval '.version' pubspec.yaml)
        echo "current_version=$current_version" >> $GITHUB_OUTPUT

    - name: Update pubspec.yaml
      if: steps.tagpr.outputs.tag != '' && steps.tagpr.outputs.tag != steps.get_current_version.outputs.current_version
      run: |
        yq eval '.version = "${{ steps.tagpr.outputs.tag }}"' pubspec.yaml -i
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add pubspec.yaml
        git commit -m "Update pubspec.yaml version to ${{ steps.tagpr.outputs.tag }}"
        git push